name: enric_morales_final_exam
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0

  firebase_auth: ^3.3.4
  flutterfire_ui: ^0.3.1
  firestore_ui: ^1.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^1.0.0


flutter:  
  uses-material-design: true